Repository HendrikPN/scigym-web, pull requests merged in 2019-06, with the labels that each got.

#28 Enhancement/mobile drawer
  public/favicon.png
  public/index.html
  public/manifest.json
  src/actions/environments.js
  src/actions/images.js
  src/components/App.js
  src/components/ExpandMoreLess.js
  src/components/Notifications.jsx
  src/components/VerificationChip.js
  src/components/auth/Auth.js
  src/components/environment/EnvironmentDetail.js
  src/components/environment/EnvironmentDetailContent.js
  src/components/files/images.jsx
  src/components/get_started/play.md
  src/components/header/Header.js
  src/components/header/SearchBar.js
  src/components/header/SearchBarEnvList.js
  src/components/home/About.js
  src/components/home/EnvironmentItem.jsx
  src/components/home/Hero.jsx
  src/components/home/Home.jsx
  src/components/home/TopicDrawer.js
  src/components/home/drawer/ChildListElement.js
  src/components/home/drawer/DrawerContent.js
  src/components/home/drawer/DrawerContentTopics.js
  src/components/home/drawer/DrawerHead.js
  src/components/home/drawer/TopicDrawer.js
  src/components/home/environment_item/EnvironmentItem.jsx
  src/components/home/environment_item/EnvironmentItemContent.js
  src/components/home/feature_cards/FeatureCardAPI.js
  src/components/home/feature_cards/FeatureCardConnect.js
  src/components/home/feature_cards/FeatureCardRL.js
  src/components/home/feature_cards/FeatureCards.js
  src/components/home/hero/Hero.jsx
  src/components/home/hero/HeroOverlay.js
  src/components/profile/Profile.jsx
  src/components/profile/Settings.jsx
  src/components/profile/SettingsItem.jsx
  src/components/profile/account/Account.jsx
  src/components/profile/account/AccountDanger.jsx
  src/components/profile/account/AccountDelete.jsx
  src/components/profile/account/AccountForm.jsx
  src/components/profile/groups/Groups.jsx
  src/components/profile/images/DeleteImage.js
  src/components/profile/images/ImageCard.js
  src/components/profile/images/Images.js
  src/components/profile/repositories/DeleteEnvironment.jsx
  src/components/profile/repositories/EnvironmentForm.jsx
  src/components/profile/repositories/EnvironmentFormControl.js
  src/components/profile/repositories/EnvironmentFormText.js
  src/components/profile/repositories/ImagePopContent.js
  src/components/profile/repositories/ImagePreview.js
  src/components/profile/repositories/Repositories.jsx
  src/components/profile/repositories/RepositoryItem.jsx
  src/components/profile/repositories/RepositoryItemFormArea.js
  src/components/profile/repositories/RepositoryList.js
  src/reducers/environments.js
  src/utils/constants.js
  src/utils/debounce.js
  src/utils/types.js
Labels: MVP, frontend

#29 updated production environment to use root URL
  src/utils/environment.js
Labels: bug, frontend

#18 Impressum added
  src/actions/contributors.js
  src/actions/projectauthors.js
  src/components/App.js
  src/components/header/ProfileMenu.js
  src/components/home/drawer/DrawerHead.js
  src/components/impressum/ContributorCard.js
  src/components/impressum/Impressum.js
  src/reducers/contributors.js
  src/reducers/index.js
  src/reducers/projectauthors.js
  src/utils/api.js
  src/utils/types.js
Labels: MVP, frontend

#32 overflow for code now supported
  src/components/get_started/Markdown.js
Labels: MVP, enhancement, frontend

#30 Bug/image upload
  src/components/environment/EnvironmentDetail.js
  src/components/home/environment_item/EnvironmentItem.jsx
  src/components/profile/images/ImageCard.js
  src/components/profile/repositories/EnvironmentFormText.js
  src/components/profile/repositories/ImagePopContent.js
  src/components/profile/repositories/ImagePreview.js
  src/utils/constants.js
Labels: MVP, backend, bug
